prestige:
  max-level: 10
  base-cost: 50000
  cost-multiplier: 1.6
  title-per-level:
    - "Nowicjusz"
    - "Osadnik"
    - "Budowniczy"
    - "Mistrz"
    - "Weteran"
    - "Elita"
    - "Mityczny"
    - "Legendarny"
    - "Niesmiertelny"
    - "Transcendentny"
  perks:
    minion-slots-every-levels: 2
    crystal-luck-percent-per-level: 4.0
    size-percent-per-level: 5.0
    extra-members-every-levels: 3
